; -- Waqas Automation Pro v2.0 Inno Setup Script --
; Compiles dist/WaqasAutomationPro into a professional Windows Installer (.exe)

#define MyAppName "Waqas Automation Pro"
#define MyAppVersion "2.0.0"
#define MyAppPublisher "Waqas Shaukat"
#define MyAppURL "https://www.facebook.com/wqas.shwkt/"
#define MyAppExeName "WaqasAutomationPro.exe"

[Setup]
; Unique AppId to prevent multi-install collisions
AppId={{D3A8F902-1402-4A2E-88D1-C990A7B29F11}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=
OutputDir=..\installer_output
OutputBaseFilename=WaqasAutomationPro_v2.0_Setup
SetupIconFile=..\app\gui\assets\logo.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Dist files generated by PyInstaller
Source: "..\dist\WaqasAutomationPro\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
